clone_depth: 1

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      MSBUILD_PLATFORM: x64
      CMAKE_BUILD_TUPLE: x64 x64
      OPENSSL_BUILD_TUPLE: x64 amd64 VC-WIN64A
      FFMPEG_BUILD_TUPLE: x64 amd64
      LIBPLACEBO_BUILD_TUPLE: x64 CLANG64
      CMAKE_ARGS: -DCMAKE_SYSTEM_VERSION=10.0.22621.0
      VULKAN_SDK: C:\Vulkan
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      MSBUILD_PLATFORM: ARM64
      CMAKE_BUILD_TUPLE: arm64 ARM64
      OPENSSL_BUILD_TUPLE: arm64 amd64_arm64 VC-WIN64-ARM
      FFMPEG_BUILD_TUPLE: arm64 amd64_arm64
      LIBPLACEBO_BUILD_TUPLE: arm64 CLANGARM64
      CMAKE_ARGS: -DCMAKE_SYSTEM_VERSION=10.0.22621.0
      VULKAN_SDK: C:\Vulkan
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS-Monterey
      MACOS_MIN: 11.0

before_build:
  - 'git submodule update --init'
  - sh: 'export SDKROOT=`xcrun --sdk macosx --show-sdk-path`'
  - cmd: 'choco install nasm -y'
  - sh: 'brew install nasm meson'
  - cmd: 'curl -O https://sdk.lunarg.com/sdk/download/latest/windows/vulkan_sdk.exe'
  - cmd: 'vulkan_sdk.exe --root %VULKAN_SDK% --accept-licenses --default-answer --confirm-command install'
  - cmd: 'cd tools'
  - cmd: 'curl -L -O https://github.com/rainers/cv2pdb/releases/download/v0.52/cv2pdb-0.52.zip'
  - cmd: '7z x *'
  - cmd: 'cd ..'

build_script:
  - cmd: 'cmd /c build-detours.bat %MSBUILD_PLATFORM%'
  - 'mkdir build'
  - 'cd build'
  - 'mkdir SDL'
  - 'cd SDL'
  - cmd: 'cmd /c ..\..\build-sdl.bat %CMAKE_BUILD_TUPLE%'
  - sh: '../../build-sdl.sh'
  - 'cd ..'
  - 'mkdir SDL_ttf'
  - 'cd SDL_ttf'
  - cmd: 'cmd /c ..\..\build-sdl-ttf.bat %CMAKE_BUILD_TUPLE%'
  - 'cd ..'
  - 'mkdir openssl'
  - cmd: 'cmd /c ..\build-openssl.bat %OPENSSL_BUILD_TUPLE%'
  - sh: '../build-openssl.sh x64 darwin64-x86_64-cc'
  - sh: '../build-openssl.sh arm64 darwin64-arm64-cc'
  - 'mkdir libplacebo'
  - cmd: 'cmd /c ..\build-libplacebo-windows.bat %LIBPLACEBO_BUILD_TUPLE%'
  - 'mkdir dav1d'
  - 'cd dav1d'
  - cmd: 'cmd /c ..\..\build-dav1d.bat %FFMPEG_BUILD_TUPLE%'
  - sh: '../../build-dav1d.sh'
  - 'cd ..'
  - 'mkdir FFmpeg'
  - cmd: 'cmd /c ..\build-ffmpeg-windows.bat %FFMPEG_BUILD_TUPLE%'
  - sh: '../build-ffmpeg-macos.sh x64 x86_64'
  - sh: '../build-ffmpeg-macos.sh arm64 arm64'
  - 'mkdir opus'
  - 'cd opus'
  - cmd: 'cmd /c ..\..\build-opus.bat %CMAKE_BUILD_TUPLE%'
  - sh: '../../build-opus.sh x64 x86_64'
  - sh: '../../build-opus.sh arm64 arm64'
  - 'cd ..'
  - 'mkdir discord-rpc'
  - 'cd discord-rpc'
  - cmd: 'cmd /c ..\..\build-discord-rpc.bat %CMAKE_BUILD_TUPLE%'
  - sh: '../../build-discord-rpc.sh x64 x86_64'
  - sh: '../../build-discord-rpc.sh arm64 arm64'
  - 'cd ..'
  - 'cd ..'
  - cmd: 'cmd /c archive.bat %MSBUILD_PLATFORM%'
  - sh: ./archive.sh

after_build:
  - cmd: appveyor PushArtifact windows-%MSBUILD_PLATFORM%.zip
  - sh: appveyor PushArtifact macos.zip

deploy: off